config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :pins
  get 'welcome/index'
  root 'welcome#index'

  get 'mypins' => 'pins#mypins'
  get 'pinsof/:user_id' => 'pins#pinsof', :as => "pinsof"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/pin.rb
class Pin < ApplicationRecord
	validates :photo, presence:true
	validates :description, presence:true
	belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :pins
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :sign_up, only: [:mail, :password, :password_confirmation, :phone]

  protected

  def configure_permitted_parameters
  	params.require(:sign_up).permit(:email, :password, :password_confirmation, :phone)
  end

end

app/controllers/pins_controller.rb
class PinsController < ApplicationController
  before_action :set_pin, only: [:show, :edit, :update, :destroy]
  before_filter :authenticate_user!, except:[:index, :show]

  def pinsof
    @user_id = params[:user_id]
    @user = User.find(@user_id)
    @pins = @user.pins
    
  end

  def mypins
    @pins = current_user.pins

  end

  # GET /pins
  # GET /pins.json
  def index
    @pins = Pin.all
  end

  # GET /pins/1
  # GET /pins/1.json
  def show
  end

  # GET /pins/new
  def new
    @pin = Pin.new
  end

  # GET /pins/1/edit
  def edit
  end

  # POST /pins
  # POST /pins.json
  def create
    @pin = Pin.new(pin_params)
    @pin.user_id = current_user


    respond_to do |format|
      if @pin.save
        format.html { redirect_to @pin, notice: 'Pin was successfully created.' }
        format.json { render :show, status: :created, location: @pin }
      else
        format.html { render :new }
        format.json { render json: @pin.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pins/1
  # PATCH/PUT /pins/1.json
  def update
    respond_to do |format|
      if @pin.update(pin_params)
        format.html { redirect_to @pin, notice: 'Pin was successfully updated.' }
        format.json { render :show, status: :ok, location: @pin }
      else
        format.html { render :edit }
        format.json { render json: @pin.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pins/1
  # DELETE /pins/1.json
  def destroy
    @pin.destroy
    respond_to do |format|
      format.html { redirect_to pins_url, notice: 'Pin was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_pin
      @pin = Pin.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def pin_params
      params.require(:pin).permit(:photo, :description, :name)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pins_helper.rb
module PinsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Pinterest</title>
    <!-- Latest compiled and minified CSS -->
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

  </head>

  <body>

	<%= render 'shared/navbar' %>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>


    <%= yield %>
  </body>
</html>

app/views/pins/_form.html.erb
<%= form_for(pin) do |f| %>
  <% if pin.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(pin.errors.count, "error") %> prohibited this pin from being saved:</h2>

      <ul>
      <% pin.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
<div class="form-group">
  <div class="field">
    <%= f.label :name, "Nombre" %>
    <%= f.text_field :name, :class => 'form-control', :placeholder => "Nombre del Pin"  %>
  </div>
</div>

<div class="form-group">
  <div class="field">
    <%= f.label :photo, "Foto" %>
    <%= f.text_field :photo, :class => 'form-control', :placeholder => "Nombre de la Foto" %>
  </div>

<div class="form-group">
  <div class="field">
    <%= f.label :description, "Descripción"%>
    <%= f.text_area :description, :class => 'form-control', :rows => "10", :cols => "30" %>
  </div>
</div>

<div class="form-group">
  <div class="actions">
    <%= f.submit "Crear", :class => "btn-primary" %>
  </div>
</div>

<% end %>

app/views/pins/edit.html.erb
<div class="container">
	<div class="row">
		<div class="col-md-6">
			<h1>Editing Pin</h1>
			<%= render 'form', pin: @pin %>
		</div>
	</div>
	<%= link_to 'Show', @pin %> |
	<%= link_to 'Back', pins_path %>
</div>

app/views/pins/index.html.erb
<div class="container">
  <p id="notice"><%= notice %></p>

  <h1>Listing Pins</h1>
    <% @pins.each do |pin| %>
    <div class="col-md-3">
      <div class="thumbnail">
        <%= pin.description %>
        <%= image_tag(pin.photo, :class => 'img-responsive') %>
        <div class="buttons" style="margin-top: 10px; margin-bottom: 10px ">
          <%= link_to 'Show', pin, :class => 'btn' %>
          <%= link_to 'Edit', edit_pin_path(pin), :class => 'btn' %>
          <%= link_to 'Destroy', pin, method: :delete, data: { confirm: 'Are you sure?' }, :class => 'btn' %>
        </div>
        
      </div>
    </div>
    <% end %>  
    
  <br>

  <%= link_to 'New Pin', new_pin_path %>
</div>

app/views/pins/mypins.html.erb
<div class="container">
  <p id="notice"><%= notice %></p>

  <h1>Listing Pins</h1>
    <% @pins.each do |pin| %>
    <div class="col-md-3">
      <div class="thumbnail">
        <%= pin.name %>
        <%= image_tag(pin.photo, :class => 'img-responsive') %>
        <%= pin.description %>
        <div class="buttons" style="margin-top: 10px; margin-bottom: 10px ">
          <%= link_to 'Show', pin, :class => 'btn' %>
          <% if user_signed_in? %>
              <%= link_to 'Edit', edit_pin_path(pin), :class => 'btn' %>
              <%= link_to 'Destroy', pin, method: :delete, data: { confirm: 'Are you sure?' }, :class => 'btn' %>
          <% end %>
        </div>
        
      </div>
    </div>
    <% end %>  
    
  <br>
<% if user_signed_in? %>
  <%= link_to 'New Pin', new_pin_path %>
<% end %>
  
</div>

app/views/pins/new.html.erb
<div class="container">
	<h1>Agrega tu nuevo Pin</h1>
	<div class="row">
		<div class="col-md-6">
			<%= render 'form', pin: @pin %>

			<p><%= link_to 'Back', pins_path %></p>
		</div>
	</div>
</div>

app/views/pins/pinsof.html.erb
<div class="container">
  <p id="notice"><%= notice %></p>

  <h1>Listing Pins</h1>
    <% @pins.each do |pin| %>
    <div class="col-md-3">
      <div class="thumbnail">
        <%= pin.name %>
        <%= image_tag(pin.photo, :class => 'img-responsive') %>
        <%= pin.description %>
        <div class="buttons" style="margin-top: 10px; margin-bottom: 10px ">
          <%= link_to 'Show', pin, :class => 'btn' %>
          <% if user_signed_in? %>
              <%= link_to 'Edit', edit_pin_path(pin), :class => 'btn' %>
              <%= link_to 'Destroy', pin, method: :delete, data: { confirm: 'Are you sure?' }, :class => 'btn' %>
          <% end %>
        </div>
        
      </div>
    </div>
    <% end %>  
    
  <br>
<% if user_signed_in? %>
  <%= link_to 'New Pin', new_pin_path %>
<% end %>
  
</div>

app/views/pins/show.html.erb
<div class="container">

	<p id="notice"><%= notice %></p>

	<p>
	  <strong>Name:</strong>
	  <%= @pin.name %>
	</p>

	<p>
	  <strong>Photo:</strong>
	  <%= image_tag(@pin.photo, :style => 'width:500px') %>
	</p>

	<p>
	  <strong>Description:</strong>
	  <%= @pin.description %>
	</p>

	<%= link_to 'Edit', edit_pin_path(@pin) %> |
	<%= link_to 'Back', pins_path %>

	<%=link_to "mas pins del mismo Usuario", pinsof_path(@pin.user.id) %>
	
</div>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-default" style="margin-bottom: 0px;">
	  <div class="container-fluid">
	    <!-- Brand and toggle get grouped for better mobile display -->
	    <div class="navbar-header">
	      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
	        <span class="sr-only">Toggle navigation</span>
	        <span class="icon-bar"></span>
	        <span class="icon-bar"></span>
	        <span class="icon-bar"></span>
	      </button>
	      <a class="navbar-brand" href="<%= root_path %>">Mi Pinterest</a>
	    </div>

	    <!-- Collect the nav links, forms, and other content for toggling -->
	    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
	      <ul class="nav navbar-nav">
	        <li><a href="#">Nosotros <span class="sr-only">(current)</span></a></li>
	        <li><a href="<%= pins_path %>">Pins</a></li>
	        <li class="dropdown">
	          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Dropdown <span class="caret"></span></a>
	          <ul class="dropdown-menu">
	            <li><a href="#">Action</a></li>
	            <li><a href="#">Another action</a></li>
	            <li><a href="#">Something else here</a></li>
	            <li role="separator" class="divider"></li>
	            <li><a href="#">Separated link</a></li>
	            <li role="separator" class="divider"></li>
	            <li><a href="#">One more separated link</a></li>
	          </ul>
	        </li>
	      </ul>
	      
	      <ul class="nav navbar-nav navbar-right">
	      	<% if current_user.nil? %>
	      		<li><a href="<%= new_user_session_path %>">Ingreso</a></li>
	        	<li><a href="<%= new_user_registration_path %>">Registro</a></li>
	        	<% else %>
	        	<li><a href="<%= destroy_user_session_path %> " data-method="delete">Salir</a></li>
	      	<% end %>
	     
	      </ul>
	    </div><!-- /.navbar-collapse -->
	  </div><!-- /.container-fluid -->
	</nav>

app/views/welcome/index.html.erb
<div class="jumbotron">
	<div class="container">
	  <h1>Welcome to my site</h1>
	  <p>...</p>
	  <p><a class="btn btn-primary btn-lg" href="#" role="button">Learn more</a></p>
	  <p><button type="button" class="btn btn-success">Success <span class="glyphicon glyphicon-thumbs-up"></span></button></p>
  	</div>
</div>
<div class="container">
	<div class="col-md-4">
		<div class="page-header">
  			<h1>Example page header <small>Subtext for header</small></h1>
		</div>
		<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Debitis a, qui tempore, tenetur optio eaque esse dolore maiores dignissimos similique itaque. Consequatur voluptate modi eum eveniet quam? Corrupti, aperiam! Quisquam, reprehenderit possimus. Maiores aut obcaecati recusandae debitis commodi autem est ipsam sint eum, natus, ad eos libero earum cupiditate saepe.</p>
	</div>
	<div class="col-md-4">
		<div class="page-header">
  			<h1>Example page header <small>Subtext for header</small></h1>
		</div>
		<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Debitis a, qui tempore, tenetur optio eaque esse dolore maiores dignissimos similique itaque. Consequatur voluptate modi eum eveniet quam? Corrupti, aperiam! Quisquam, reprehenderit possimus. Maiores aut obcaecati recusandae debitis commodi autem est ipsam sint eum, natus, ad eos libero earum cupiditate saepe.</p>
	</div>

	<div class="col-md-4">
		<div class="page-header">
  			<h1>Example page header <small>Subtext for header</small></h1>
		</div>
		<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Debitis a, qui tempore, tenetur optio eaque esse dolore maiores dignissimos similique itaque. Consequatur voluptate modi eum eveniet quam? Corrupti, aperiam! Quisquam, reprehenderit possimus. Maiores aut obcaecati recusandae debitis commodi autem est ipsam sint eum, natus, ad eos libero earum cupiditate saepe.</p>
	</div>


	<div class="row">
  		<div class="col-xs-6 col-md-3">
    		<a href="#" class="thumbnail">
      			<img src="..." alt="...">
    		</a>
  		</div>
  ...
</div>




</div>

	